name: smatii
description: A new Flutter project.
homepage: https://bitbucket.org/
version: 1.0.0+1
publish_to: none #Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  device_info_plus: ^8.0.0
  dio: ^5.1.1
  equatable: ^2.0.5
  firebase_analytics: ^10.0.4
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4
  firebase_dynamic_links: ^5.0.9
  firebase_messaging: ^14.5.0
  flutter_flavor: ^3.1.1
  flutter_local_notifications: ^14.0.0+2
  flutter_naver_map:
    git:
      url: https://github.com/betrider/flutter_naver_map.git
      ref: 1.0.4
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.5
  fluttertoast: ^8.1.2
  geolocator: ^9.0.2
  go_router: ^7.0.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  kakaomap_webview: ^0.6.2
  logger: ^1.3.0
  package_info_plus: ^3.0.2
  path: ^1.8.2
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.1.0
  uni_links: ^0.5.1
  upgrader: ^6.0.1
  url_launcher: ^6.1.7
  webview_flutter: ^3.0.4
  # share_plus: ^6.3.0
  # image_picker: ^0.8.6
  # file_picker: ^5.2.4
  cached_network_image: ^3.2.3
  syncfusion_flutter_charts: ^21.2.4
  dropdown_button2: ^2.1.3
  easy_rich_text: ^2.0.0
  dynamic_color: ^1.6.5
  # scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true

  #svg파일 ttf로 변환 : https://www.fluttericon.com/
  #참고 ttf 파일 : https://www.fontspace.com/social-media-color-font-f30260
  fonts:
    - family: SocialMediaIcons
      fonts:
        - asset: assets/fonts/SocialMediaIcons.ttf

    # 한글용 폰트(android,ios) - Pretendard
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900

    # 영문용 폰트(android) - Helvetica
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-UltLtEx.otf
          weight: 100
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-ThEx.otf
          weight: 200
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-LtEx.otf
          weight: 300
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-Ex.otf
          weight: 400
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-MdEx.otf
          weight: 500
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-HvEx.otf
          weight: 600
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-BdEx.otf
          weight: 700
        - asset: assets/fonts/helvetica/HelveticaNeueLTStd-BlkEx.otf
          weight: 800

    # 영문용 폰트(ios) - SF pro
    - family: SFPro
      fonts:
        - asset: assets/fonts/sfpro/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: assets/fonts/sfpro/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: assets/fonts/sfpro/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/sfpro/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/sfpro/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/sfpro/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/sfpro/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/sfpro/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/sfpro/SF-Pro-Text-Black.otf
          weight: 900

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/launcher/
    - assets/gif/
    - assets/svg/

# flutter_launcher_icons 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/launcher/flutter_ui_dev_logo.png"
  android: true
  ios: true

# flutter_native_splash 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_native_splash:create 생성
# flutter pub run flutter_native_splash:remove 삭제
flutter_native_splash:
  image: "assets/images/img-splash-drone.png" # 중앙 로고 이미지
  color: "#197AEA" # 배경색
  branding: "assets/images/img-logo-smatii.png" # 하단 브랜딩 이미지
  android_12:
    image: "assets/images/img-splash-drone.png" # 중앙 로고 이미지
    color: "#197AEA" # 배경색
    branding: "assets/images/img-logo-smatii.png" # 하단 브랜딩 이미지
  fullscreen: true # status bar 포함 여부
  android: true
  ios: true
