// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdW1GIkh9UIEuzQ4UhxyHePX3GjcEZ53s',
    appId: '1:699744279255:android:ccdccf326ae0f2e0692e92',
    messagingSenderId: '699744279255',
    projectId: 'smatii',
    storageBucket: 'smatii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-3rCak4xCsu6IJPzd0qt0_lDAkywsg8',
    appId: '1:699744279255:ios:8d8b9a354eaa5211692e92',
    messagingSenderId: '699744279255',
    projectId: 'smatii',
    storageBucket: 'smatii.appspot.com',
    androidClientId: '699744279255-25tts6d0r6fja0ol80gp8qicpp0s89ko.apps.googleusercontent.com',
    iosClientId: '699744279255-ec6inmm2l8rjrmlnt8tsio8t968s9m2b.apps.googleusercontent.com',
    iosBundleId: 'com.smatii.readytofly',
  );
}
